apiVersion: v1
data:
  opencode.json: |
{{ toJson .Values.opencodeConfig | indent 4 }}
kind: ConfigMap
metadata:
  annotations:
    controller.devfile.io/mount-path: /home/user/.config/opencode/config-map
  labels:
    controller.devfile.io/mount-to-devworkspace: "true"
    controller.devfile.io/watch-configmap: "true"
  name: opencode-config